### ISSUE TITLE
Several games do not work after the introduction.

### ISSUE THREAD

**Issue by Guardian1676** [xqemu/xqemu#287] opened 2020-08-19 00:27 UTC
I've been trying the following games but they don't work after the introduction:

Black
![image](https://user-images.githubusercontent.com/65382849/90578045-e4949a00-e187-11ea-8e13-624b56ef1450.png)

Mortal Kombat Shaolin Monks
![image](https://user-images.githubusercontent.com/65382849/90578134-2291be00-e188-11ea-8ed7-e26f07a27afb.png)

Conker Live And Reloaded
![image](https://user-images.githubusercontent.com/65382849/90578210-579e1080-e188-11ea-8571-8dcf9ec21211.png)

Urban Chaos
![image](https://user-images.githubusercontent.com/65382849/90578278-84522800-e188-11ea-9c73-3a7caa88a8dc.png)

I have:
Ryzen 5 3600
RTX 2060 Super
16 GB Ram GDDR4 3000

Thank you very much for your time

**Comment by JayFoxRox** [comment] 2020-08-19 09:16
> I've been trying the following games but they don't work after the introduction

These are known, but somewhat undocumented, issues.

If video playback hangs, it usually comes down to #24 - because of missing audio playback, it will refuse to advance video playback (to avoid audio and video running out of sync).
You can typically work around it by hitting the A or Start button a number of times, so you might be able to skip the video before it even hangs.

However, XQEMU still has many other issues which will make it impossible to actually play (or enjoy) those games.

> Ryzen 5 3600
> RTX 2060 Super
> 16 GB Ram GDDR4 3000

These are issues in XQEMU code which will happen on every machine; so your machine details aren't really relevant.

---

We typically track bug reports for specific hardware features and not how they manifest in each individual game (unless there's a very specific kind of bug). In other words: we are tracking causes, not symptoms.

Issues for most potential root causes for such symptoms already existed, so I'm sure that each of these games will be fixed when we resolve some other, already existing, issues.

Managing this issue with a proper fix would be difficult (as we'd be "half-closing" it if we can't fix all games at once).
So while you are describing a valid problem, it's difficult to track "this set of games won't work".

So I'm going to close this issue, because we can't know that all of those games are affected by the same problem (or that a fix would fix all of them at once), and because it's tracking a very loosely defined symptom, but not a cause.

Closed.

**Closed by JayFoxRox** 2020-08-19 09:16 UTC
