### ISSUE TITLE
eeprom msft violation

### ISSUE THREAD

**Issue by JazzMaster** [xqemu/xqemu#228] opened 2019-05-28 20:00 UTC
read the file in one byte(ff) at a time from disk- and demand a file before starting the emulator.
here is your patch.

Thanks for the 1.0 eeprom.

xbox.c:

// XBOX_TODO: Should be passed in through configuration -and is illegal to distribute
const uint8_t default_eeprom[] = {};

**Comment by dracc** [comment] 2019-05-28 20:02
Read for a minute longer and you'll see it's the bunnie eeprom which is provided under a FOSS license.

**Comment by mborgerson** [comment] 2019-05-28 21:09
Duplicate of #28

**Closed by mborgerson** 2019-05-28 21:09 UTC
